# Generated by Django 5.1.2 on 2024-11-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
